site:
  url: https://tanren.fun
  title: Tanren
  start_page: docs::index.adoc

# content:
#   sources:
#   - url: https://git.tanren.fun/primejade/blog.git
#     branches: linux
#     start_paths: /
#   - url: https://git.tanren.fun/primejade/blog.git
#     branches: git
#     start_paths: /
#   - url: https://git.tanren.fun/primejade/blog.git
#     branches: container
#     start_paths: /
#   - url: https://git.tanren.fun/primejade/blog.git
#     branches: programming
#     start_paths: /

runtime:
  cache_dir: ./cache/antora

  # log: 
  #   format: json 
  #   failure_level: warn 
  #   level: all 
  #   level_format: number 
  #   destination: 
  #     file: ./antora.log 
  #     append: true 
  #     buffer_size: 4096 
  #     sync: true 

# network: 
#   http_proxy: http://127.0.0.1:20171
#   https_proxy: http://127.0.0.1:20171

ui:
  bundle:
    # url: https://gitlab.com/hos-blog/antora-ui-hos/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://github.com/hossein-lap/asciidoctor-docs-ui/releases/download/prod-350/ui-bundle.zip
    # url: https://github.com/hossein-lap/asciidoctor-docs-ui/releases/download/prod-351/ui-bundle.zip
    url: ./ui-bundle.zip
    snapshot: true
  # default_layout: article

output:
  clean: true
  dir: ./build

asciidoc: 
  attributes: 
    skip-front-matter: true
    icons: font
    icon-set: fi
    sectnums: false
    toc: false
    source-highlighter: highlight.js
    # highlightjs-theme: tomorrow-night
    # pygments-style: solarized-light
    # source-highlighter: rouge
    # rouge-style: solarized-light

