
== Python Variables

=== Variables

Variables are containers for storing data values.

==== Creating Variables

Python has no command for declaring a variable.

.A variable is created the moment you first assign a value to it.
****
----
x = 5
y = "John"
print(x)
print(y)
----

.Output
....
5
John
....
****

Variables do not need to be declared with any particular type, and can even change type after they have been set.

----
x = 4          # x is of type int
x = "Sally"    # x is now of type str
print(x)
----

.Output
....
Sally
....

==== Casting

If you want to specify the data type of a variable, this can be done with casting.

----
x = str(3)         # x will be '3' -> string
y = int(3)         # y will be 3 -> integer
z = float(3)       # z will be 3.0 -> float
----

.Get the Type
****
You can get the data type of a variable with the `type()` function.

----
x = 5
y = "John"
print(type(x))
print(type(y))
----

.Output
....
<class 'int'>
<class 'str'>
....
****

[NOTE]
====
You will learn more about _data types_ and _casting_ later in this tutorial.
====

.Single or Double Quotes?
String variables can be declared either by using single or double quotes:

----
x = "John"
# is the same as
x = 'John'
----

==== Case-Sensitive

Variable names are case-sensitive.

----
a = 4
A = "Sally"
#A will not overwrite a
----

=== Variable Names

A variable can have a short name (like x and y) or a more descriptive name
(`age`, `carname`, `total_volume`). Rules for Python variables:

.A variable name:
* Must start with a letter or the underscore character
* Cannot start with a number
* Can only contain alpha-numeric characters and underscores (A-z, 0-9, and `_`)
* Variable names are case-sensitive (age, Age and AGE are three different
  variables)

----
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"
----

----
2myvar = "John"
my-var = "John"
my var = "John"
----

[NOTE]
====
Remember that variable names are _case-sensitive_.
====

=== Multi Words Variable Names

Variable names with more than one word can be difficult to read.

There are several techniques you can use to make them more readable:

.Camel Case
Each word, except the first, starts with a capital letter:

----
myVariableName = "John"
----

.Pascal Case
Each word starts with a capital letter:

----
MyVariableName = "John"
----

.Snake Case
Each word is separated by an underscore character:

----
 my_variable_name = "John"
----

=== Assign Multiple Values

.Many Values to Multiple Variables
****
Python allows you to assign values to multiple variables in one line:

----
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)
----

.Output
....
Orange
Banana
Cherry
....
****

[NOTE]
====
Make sure the number of variables matches the number of values, or else you
will get an error.
====

.One Value to Multiple Variables
****
And you can assign the same value to multiple variables in one line:

----
x = y = z = "Orange"
print(x)
print(y)
print(z)
----

.Output
....
Orange
Orange
Orange
....
****

.Unpack a Collection
****
If you have a collection of values in a list, tuple etc. Python allows you to
extract the values into variables. This is called unpacking.

----
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)
----

.Output
....
apple
banana
cherry
....
****

You will learn more about this in xref:#_python_unpack_tuples[Unpack Tuple] chapter.

=== Output Variables

.Output Variables
****
The Python `print()` function is often used to output variables.

----
x = "Python is awesome"
print(x)
----

.Output
....
Python is awesome
....
****

In the `print()` function, you output multiple variables, separated by a comma:

----
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)
----

.Output
....
Python is awesome
....

You can also use the `+` operator to output multiple variables:

----
x = "Python "
y = "is "
z = "awesome"
print(x + y + z)
----

.Output
....
Python is awesome
....

[NOTE]
====
Notice the space character after "Python " and "is ", without them the result
would be "Pythonisawesome".
====

For numbers, the `+` character works as a mathematical operator:

----
x = 5
y = 10
print(x + y)
----

.Output
....
15
....

In the `print()` function, when you try to combine a string and a number with
the `+` operator, Python will give you an error:

----
x = 5
y = "John"
print(x + y)
----

.Error
[IMPORTANT]
====
....
Traceback (most recent call last):
  File "/home/hos/Documents/teach/python/en/test.py",
  line 3, in <module>
    print(x + y)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
....
====

The best way to output multiple variables in the `print()` function is to
separate them with commas, which even support different data types:

----
x = 5
y = "John"
print(x, y)
----

.Output
....
5 John
....

=== Global Variables

Variables that are created outside of a function (as in all of the examples
above) are known as global variables.

Global variables can be used by everyone, both inside of functions and outside.

----
x = "awesome"

def myfunc():
    print("Python is " + x)

myfunc()
----

.Output
....
Python is awesome
....

If you create a variable with the same name inside a function, this variable
will be local, and can only be used inside the function. The global variable
with the same name will remain as it was, global and with the original value.

----
x = "awesome"

def myfunc():
    x = "fantastic"
    print("Python is " + x)

myfunc()

print("Python is " + x)
----

.Output
....
Python is fantastic
Python is awesome
....

==== The `global` Keyword

Normally, when you create a variable inside a function, that variable is local,
and can only be used inside that function.

To create a global variable inside a function, you can use the `global` keyword.

****
If you use the global keyword, the variable belongs to the global scope:

----
def myfunc():
    global x
    x = "fantastic"

myfunc()

print("Python is " + x)
----

.Output
....
Python is fantastic
....
****

Also, use the `global` keyword if you want to change a global variable inside a
function.

****
To change the value of a global variable inside a function, refer to the
variable by using the `global` keyword:

----
x = "awesome"

def myfunc():
    global x
    x = "fantastic"

    myfunc()

    print("Python is " + x)
----

.Output
....
Python is fantastic
....
****

=== Exercise

.Create a variable named `carname` and assign the value `Volvo` to it
....
        = "     "
....

