== Python Tuples

----
mytuple = ("apple", "banana", "cherry")
----

Tuples are used to store multiple items in a single variable.

Tuple is one of 4 built-in data types in Python used to store collections of
data, the other 3 are:

. List
. Set
. Dictionary

All with different qualities and usage. A tuple is a collection which is
ordered and *unchangeable*. Tuples are written with round brackets.

.Create a Tuple
****
----
thistuple = ("apple", "banana", "cherry")
print(thistuple)
----

.Output
....
('apple', 'banana', 'cherry')
....
****

==== Tuple Items

Tuple items are ordered, unchangeable, and allow duplicate values.

Tuple items are indexed, the first item has index `[0]` the second item
has index `[1]` etc.

==== Ordered

When we say that tuples are ordered, it means that the items have a defined
order, and that order will not change.

==== Unchangeable


Tuples are unchangeable, meaning that we cannot change, add or remove items
after the tuple has been created.

==== Allow Duplicates

Since tuples are indexed, they can have items with the same value:

.Tuples allow duplicate values
****
----
thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)
----

.Output
....
('apple', 'banana', 'cherry', 'apple', 'cherry')
....
****

==== Tuple Length

To determine how many items a tuple has, use the `len()` function:

.Print the number of items in the tuple
****
----
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))
----

.Output
....
3
....
****

==== Create Tuple With One Item

To create a tuple with only one item, you have to add a comma after the item,
otherwise Python will not recognize it as a tuple.

.One item tuple, remember the comma
****
----
thistuple = ("apple",)
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))
----

.Output
....
<class 'tuple'>
<class 'str'>
....
****

==== Tuple Items - Data Types

Tuple items can be of any data type:

.String, int and boolean data types
----
tuple1 = ("apple", "banana", "cherry")
tuple2 = (1, 5, 7, 9, 3)
tuple3 = (True, False, False)
----

.Tuples can contain different data types
----
tuple1 = ("abc", 34, True, 40, "male")
----

==== type()

From Python's perspective, tuples are defined as objects with the data type 'tuple':

....
 <class 'tuple'>
....

.What is the data type of a tuple?
****
----
mytuple = ("apple", "banana", "cherry")
print(type(mytuple))
----

.Output
....
 <class 'tuple'>
....
****

==== The tuple() Constructor

It is also possible to use the `tuple()` constructor to make a tuple.

.Using the tuple() method to make a tuple
*****
-----
# note the double round-brackets
thistuple = tuple(("apple", "banana", "cherry"))
print(thistuple)
-----

.Output
.....
('apple', 'banana', 'cherry')
.....
*****

=== Access Tuple Items

==== Access Items

Tuple items are indexed and you can access them by referring to the index number:

.Print the second item of the tuple
****
----
thistuple = ("apple", "banana", "cherry")
print(thistuple[1])
----

.Output
....
banana
....
****

[TIP]
====
The first item has index 0.
====

==== Negative Indexing

Negative indexing means start from the end

`-1` refers to the last item, `-2` refers to the second last item etc.

.Print the last item of the tuple
****
----
thistuple = ("apple", "banana", "cherry")
print(thistuple[-1])
----

.Output
....
cherry
....
****

==== Range of Indexes

You can specify a range of indexes by specifying where to start and where to
end the range.

When specifying a range, the return value will be a new tuple with the
specified items.

.Return the third, fourth, and fifth item
****
----
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])
----

.Output
....
('cherry', 'orange', 'kiwi')
....
****

[TIP]
====
The search will start at index 2 (included) and end at index 5 (not included).
====

[TIP]
====
Remember that the first item has index 0.
====

By leaving out the start value, the range will start at the first item:

.This example returns the items from the beginning to, but NOT including, "kiwi"
****
----
thistuple = ("apple", "banana", "cherry", "orange",
				"kiwi", "melon", "mango")
print(thistuple[:4])
----

.Output
....
('apple', 'banana', 'cherry', 'orange')
....
****

By leaving out the end value, the range will go on to the end of the tuple.

.This example returns the items from "cherry" to the end
****
----
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:])
----

.Output
....
('cherry', 'orange', 'kiwi', 'melon', 'mango')
....
****

==== Range of Negative Indexes

Specify negative indexes if you want to start the search from
the end of the tuple:

\begin{ebox}
This example returns the items from "orange" (-4) to, but NOT including "mango" (-1):
	\begin{lstlisting}
thistuple = ("apple", "banana", "cherry", "orange",
                "kiwi", "melon", "mango")
print(thistuple[-4:-1])
	\end{lstlisting}
\tcblower
	\begin{vercode}
('orange', 'kiwi', 'melon')
	\end{vercode}
\end{ebox}

==== Check if Item Exists


To determine if a specified item is present in a tuple use the `in` keyword:

\begin{ebox}
Check if "apple" is present in the tuple:
	\begin{lstlisting}
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
    print("Yes, 'apple' is in the fruits tuple")
	\end{lstlisting}
\tcblower
	\begin{vercode}
Yes, 'apple' is in the fruits tuple
	\end{vercode}
\end{ebox}
\begin{nbox}
	Accessing tuple items is just like accessing list items
\end{nbox}

=== Update Tuples


Tuples are unchangeable, meaning that you cannot change, add, or remove items
once the tuple is created.

But there are some workarounds.


==== Change Tuple Values


Once a tuple is created, you cannot change its values. Tuples are
\textbf{unchangeable}, or \textbf{immutable} as it also is called.

But there is a workaround. You can convert the tuple into a list, change the
list, and convert the list back into a tuple.

\begin{ebox}
Convert the tuple into a list to be able to change it:
	\begin{lstlisting}
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)
	\end{lstlisting}
\tcblower
	\begin{vercode}
('apple', 'kiwi', 'cherry')
	\end{vercode}
\end{ebox}

==== Add Items


Since tuples are immutable, they do not have a build-in `append()` method,
but there are other ways to add items to a tuple.

\quad
\textbf{1. Convert into a list:}
		Just like the workaround for changing a tuple, you can convert it into
		a list, add your item(s), and convert it back into a tuple.

\begin{ebox}
Convert the tuple into a list, add "orange", and convert it back into a tuple:
	\begin{lstlisting}
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)
print(thistuple)
	\end{lstlisting}
\tcblower
	\begin{vercode}
('apple', 'banana', 'cherry', 'orange')
	\end{vercode}
\end{ebox}

\quad
\textbf{2. Add tuple to a tuple:}
You are allowed to add tuples to tuples, so if you want to add one item, (or
many), create a new tuple with the item(s), and add it to the existing tuple:

\begin{ebox}
Create a new tuple with the value "orange", and add that tuple:
	\begin{lstlisting}
thistuple = ("apple", "banana", "cherry")
y = ("orange",)
thistuple += y

print(thistuple)
	\end{lstlisting}
\tcblower
	\begin{vercode}
('apple', 'banana', 'cherry', 'orange')
	\end{vercode}
\end{ebox}

\begin{nbox}
When creating a tuple with only one item, remember to include a comma
after the item, otherwise it will not be identified as a tuple.
\end{nbox}

==== Remove Items


\begin{nbox}
You cannot remove items in a tuple.
\end{nbox}

Tuples are \textbf{unchangeable}, so you cannot remove items from it, but you
can use the same workaround as we used for changing and adding tuple items:

\begin{ebox}
Convert the tuple into a list, remove "apple", and convert it back into a tuple:
	\begin{lstlisting}
 thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)
	\end{lstlisting}
\end{ebox}

Or you can delete the tuple completely:

\begin{abox}
The `del` keyword can delete the tuple completely:
	\begin{lstlisting}
thistuple = ("apple", "banana", "cherry")
del thistuple
#this will raise an error because the tuple no longer exists
print(thistuple)
	\end{lstlisting}
\tcblower
	\begin{vercode}
Traceback (most recent call last):
  File "/home/hos/Documents/teach/python/en/test.py", line 3,
  in <module>
    print(thistuple) #this will raise an error
    because the tuple no longer exists
NameError: name 'thistuple' is not defined
	\end{vercode}
\end{abox}

=== Unpack Tuples}\label{pyUnpackTuple



==== Unpacking a Tuple


When we create a tuple, we normally assign values to it. This is called
"packing" a tuple:

\begin{ebox}
Packing a tuple:
	\begin{lstlisting}
fruits = ("apple", "banana", "cherry")
	\end{lstlisting}
\end{ebox}

But, in Python, we are also allowed to extract the values back into variables.
This is called "unpacking":

\begin{ebox}
Unpacking a tuple:
	\begin{lstlisting}
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)
	\end{lstlisting}
\tcblower
	\begin{vercode}
apple
banana
cherry
	\end{vercode}
\end{ebox}

[TIP]
====
The number of variables must match the number of values in the tuple, if not,
you must use an asterisk to collect the remaining values as a list.
====

==== Using Asterisk\lcode{*}


If the number of variables is less than the number of values, you can add an
`*` to the variable name and the values will be assigned to the variable
as a list:

.Assign the rest of the values as a list called "red"
****
----
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)
----

.Output
....
apple
banana
['cherry', 'strawberry', 'raspberry']
....
****

If the asterisk is added to another variable name than the last, Python will
assign values to the variable until the number of values left matches the
number of variables left.

.Add a list of values the "tropic" variable
****
----
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)
----

.Output
....
apple
['mango', 'papaya', 'pineapple']
cherry
....
****

=== Loop Tuples

==== Loop Through a Tuple

You can loop through the tuple items by using a `for` loop.

.Iterate through the items and print the values
****
----
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
    print(x)
----

.Output
....
apple
banana
cherry
....
****

Learn more about `for` loops in xref:#_python_for_loop[Python For Loop] chapter.

==== Loop Through the Index Numbers


You can also loop through the tuple items by referring to their index number.

Use the `range()` and `len()` functions to create a suitable iterable.

.Print all items by referring to their index number
****
----
thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
    print(thistuple[i])
----

.Output
....
apple
banana
cherry
....
****

==== Using a While Loop

You can loop through the list items by using a `while` loop.

Use the `len()` function to determine the length of the tuple, then start
at 0 and loop your way through the tuple items by refering to their indexes.

Remember to increase the index by 1 after each iteration.

.Print all items, using a `while` loop to go through all the index numbers
****
----
thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
    print(thistuple[i])
    i = i + 1
----

.Outoput
....
apple
banana
cherry
....
****

Learn more about `while` loops in xref:#_python_while_loop[Python While Loop] chapter.

=== Join Tuples

==== Join Two Tuples

To join two or more tuples you can use the \code{+} operator:

.Join two tuples
****
----
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)
----

.Output
....
('a', 'b', 'c', 1, 2, 3)
....
****

==== Multiply Tuples

If you want to multiply the content of a tuple a given number of times, you can
use the `*` operator:

.Multiply the fruits tuple by 2
****
----
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)
----

.Output
....
('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')
....
****

You can see a set of built-in Tuple methods in xref:#_python_tuple_method[Python Tuple Method] section

=== Tuple Exercises

.Print the first item in the `fruits` tuple.
[NOTE]
====
----
fruits = ("apple", "banana", "cherry")
         
----
====

